from logging import Logger
from typing import Protocol, Any, Dict, Optional
from terrasnek.api import ListAllProtocol
from terrasnek.endpoint import TFCEndpoint

class TFCWorkspaces(ListAllProtocol, TFCEndpoint):
    def create(self, payload: dict) -> dict: ...
    def destroy(self, workspace_id: str) -> dict: ...
    def force_unlock(self, workspace_id: str) -> Any: ...
    def lock(self, workspace_id: str, payload: Dict) -> Any: ...
    def list(
        self,
        page: Optional[int] = None,
        page_size: Optional[int] = None,
        include: Optional[str] = None,
        search: Optional[str] = None,
        filters: Optional[str] = None,
    ) -> Any: ...
    def show(
        self,
        workspace_name: Optional[str] = None,
        workspace_id: Optional[str] = None,
        include: Optional[str] = None,
    ) -> Any: ...
    def unlock(self, workspace_id: str) -> Any: ...
    def update(
        self,
        payload: Dict,
        workspace_name: Optional[str] = None,
        workspace_id: Optional[str] = None,
    ) -> Any: ...
    def assign_ssh_key(self, workspace_id: str, payload: Dict) -> Any: ...
    def unassign_ssh_key(self, workspace_id: str, payload: Dict) -> Any: ...
    def get_remote_state_consumers(
        self,
        workspace_id: str,
        page: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> Any: ...
    def replace_remote_state_consumers(
        self, workspace_id: str, payload: Dict
    ) -> Any: ...
    def delete_remote_state_consumers(
        self, workspace_id: str, payload: Dict
    ) -> Any: ...
    def list_tags(self, workspace_id: str) -> Any: ...
    def add_tags(self, workspace_id: str, payload: Dict) -> Any: ...
    def list_all_resources(self, workspace_id: str): ...
    def remove_tags(self, workspace_id: str, payload: Dict) -> Any: ...
